# QUESTION 1 :

Write a Python program to convert an array to an ordinary list with the same items.

In [1]:
a=int(input("a="))
b=int(input("b="))
a<b
c=int(input("c="))
d=int(input("d="))
L=list
import numpy as np
e= np.random.randint(a,b,(c,d))
L = e.tolist()
print("Convert e to a list : ",L)

a=0
b=5
c=1
d=6
Convert e to a list :  [[3, 1, 3, 0, 0, 0]]


# QUESTION 2 :

Write a NumPy program to compute the sum of the diagonal element of a given array.

In [2]:
f=int(input("f="))
g=int(input("g="))
f<g
h=int(input("h="))
i=int(input("i="))
h=i
import numpy as np
j= np.random.randint(f,g,(h,i))
print(j)

f=1
g=6
h=5
i=5
[[4 1 1 1 3]
 [1 3 2 2 3]
 [1 4 2 1 5]
 [4 3 3 3 5]
 [4 4 1 5 1]]


In [3]:
SUM= int()
SUM =  np.trace(j)
print("La somme des valeurs diagonales est :", SUM)

La somme des valeurs diagonales est : 13


# QUESTION 3 :

Given an array of your choice, get all the values higher than X :
if a = [[1,2],[3,5]] and x = 3 : then 3 and 5 are higher than 2. 

In [5]:
a=int(input("a="))
b=int(input("b="))
a<b
c=int(input("c="))
d=int(input("d="))
L=list
import numpy as np
e= np.random.randint(a,b,(c,d))
print(e)

a=1
b=10
c=5
d=5
[[8 6 4 8 6]
 [4 9 4 4 8]
 [1 1 4 6 4]
 [7 7 7 4 5]
 [9 9 2 3 9]]


In [8]:
x=int(input("x="))
SUM=0
for i in range(0,len(e)):
    for j in range(len(e[i])):
        r=e[i][j]
        if r>x:
            SUM+=1
print(SUM)

x=7
7


# QUESTION 4 :

Given two arrays A&B having the same shape. 
The task is to apply addition by hand : C is the new array. 

In [9]:
a=int(input("a="))
b=int(input("b="))
a<b
c=int(input("c="))
d=int(input("d="))
L=list
import numpy as np
e= np.random.randint(a,b,(c,d))
f= np.random.randint(a,b,(c,d))
print(e)
print(f)

a=1
b=4
c=5
d=5
[[1 1 1 3 3]
 [3 1 3 2 2]
 [1 3 1 1 2]
 [3 3 3 2 3]
 [2 1 2 1 3]]
[[2 1 3 2 3]
 [1 1 3 2 3]
 [2 3 1 2 3]
 [1 2 1 2 3]
 [3 2 3 1 2]]


In [10]:
h=[]
for i in range(0,len(e)):
    l=[]
    for j in range(len(e[i])):
        r = e[i][j] + f[i][j]
        l.append(r)
    h.append(l)
print(h)

[[3, 2, 4, 5, 6], [4, 2, 6, 4, 5], [3, 6, 2, 3, 5], [4, 5, 4, 4, 6], [5, 3, 5, 2, 5]]


# QUESTION 5:

Write a NumPy program to subtract the mean of each row of a given matrix.

In [15]:
a=int(input("a="))
b=int(input("b="))
a<b
c=int(input("c="))
d=int(input("d="))
import numpy as np
e= np.random.randint(a,b,(c,d))
print(e)

a=1
b=5
c=5
d=5
[[2 1 4 1 1]
 [2 4 4 2 3]
 [1 2 4 4 1]
 [3 3 1 1 1]
 [4 2 3 1 1]]


In [17]:
h=[]
for i in range(0,len(e)):
    s=0
    for j in range(len(e[i])):
        s=s+e[i][j]
    k=s/len(e)
    h.append(k)
print(h)

[1.8, 3.0, 2.4, 1.8, 2.2]
